### ISSUE TITLE
Alterar o nome dos campos

### ISSUE THREAD

**Issue by Glaugobira** [guilhermeforprojeto/cadastro_dos_doadores#13]
Ajustar o nome dos campos de acordo com o print:

![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/147184432/6f721792-a1b0-48f1-8931-0ef87808b8ae)

**Comment by guilhermeforprojeto** [comment]
![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/24197003/7722764e-42a9-408e-ae59-51ddca3b61a4)
