### ISSUE TITLE
#002 - Alterar tela de cadastro das sacolas

### ISSUE THREAD

**Issue by Glaugobira** [guilhermeforprojeto/cadastro_dos_doadores#14]
> Excluir menu de cadastro das 'Frentes'

> Cadastrar o nome das frentes direto no banco para aparecer na listagem

> Na tela de cadastro de sacola alterar o campo 'Nome do Assistido' para ser campo texto aberto para vincular na mesma tela : Código sacola, Frente e Nome assistido.

![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/147184432/bba22acd-ce74-43b1-819b-4eaca045ab84)

**Comment by guilhermeforprojeto** [comment]
![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/24197003/8f70ed86-55ad-498a-8bc7-ee55cbf538e0)
