### ISSUE TITLE
Tirar mensagem de campo obrigatório - cadastro de célula

### ISSUE THREAD

**Issue by Glaugobira** [guilhermeforprojeto/cadastro_dos_doadores#15]
Retirar obrigatoriedade do campo 'Nome do líder' e 'Contato líder'.

Ou seja, permitir salvar só com o nome da célula.

![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/147184432/c0f4c6d0-a93a-4dfc-9e2e-7463134729b7)

**Comment by guilhermeforprojeto** [comment]
Caiu  por terra
