### ISSUE TITLE
Cadastro Sacolinhas - Dúvida Código

### ISSUE THREAD

**Issue by mapf45** [guilhermeforprojeto/cadastro_dos_doadores#4]
![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/147186718/6a44376f-0a72-440c-af1b-0f4b478342ba)

Dúvida: quando formos cadastrar a sacolinha, entraremos com a siglan, por exemplo TAM (Tamarutaca), os proximos 3 digitos, serão preenchidos automaticamente, ou teremos que entrar com os digitos tambem?

Por exemplo:

TAM001 
TAM002
TAM003

**Comment by guilhermeforprojeto** [comment]
Sera automaticamente ele ja vai filtrando conforme vc digita

**Comment by Glaugobira** [comment]
> Sera automaticamente ele ja vai filtrando conforme vc digita

Mas se nós que estaremos criando esses códigos, como que vai gerar automaticamente? acho que vai ficar muito complexo isso, pq também vai mudar  o prefixo de acordo com a frente. rs

**Comment by guilhermeforprojeto** [comment]
![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/24197003/84b380c7-6cb7-4a82-9501-12a9eb9d4ed4)
