### ISSUE TITLE
Campo Observações

### ISSUE THREAD

**Issue by mapf45** [guilhermeforprojeto/cadastro_dos_doadores#5]
![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/147186718/be140e4c-b054-40ae-a9a9-a6dba12a9f29)

Percebi que ele reclama se deixar sem alguma coisa peenchida no comentário.

Em todos os campos de observações, está acontecendo isso.

Seria interessante não ser obrigatório.

**Comment by Glaugobira** [comment]
Concordo que não deve ser obrigatório

**Comment by guilhermeforprojeto** [comment]
![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/24197003/bea2df15-b1b5-472b-8a28-31a777f0a19b)
