### ISSUE TITLE
#001 - Doação da mesma Sacolinha

### ISSUE THREAD

**Issue by mapf45** [guilhermeforprojeto/cadastro_dos_doadores#6]
![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/147186718/8db5f7e7-4e6d-42b2-8b43-53b09ec2a259)

Depois de feita a doação da sacolinha, codigo TQB001, ela deveria desaparecer da lista,  se possível, pois é possível doar ela novamente. 
Obs. se estiver no sonho, desconsidere, kkkk

Na pratica não vai acontecer, Deus queira, porque a assitente vai estar com a sacolinha com código na mão, vai preencher e vida que segue

**Comment by Glaugobira** [comment]
A ideia é uma vez doada, realmente não aparecer mais na pesquisa. Pode incluir uma mensagem de "Sacolinha doada" tipo como se fosse um "código incorreto'' sabe?

**Comment by guilhermeforprojeto** [comment]
A mesma sacola esta aparecendo na lista mesmo apos ja ter sido doada como pode ver no print a baixo

![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/24197003/63958e72-909c-4278-b0d8-aaae73ff6c5a)

**Comment by guilhermeforprojeto** [comment]
REsolvido, agora so aparece sacolas não registradas na hroa de selecionar 


[Gravação de tela de 2024-09-07 00-49-30.webm](https://github.com/user-attachments/assets/8ef95399-c0c4-475e-98e9-a629d12c0551)
