### ISSUE TITLE
#003 - Limpar campo de pesquisa após selecionar sacolinha

### ISSUE THREAD

**Issue by Glaugobira** [guilhermeforprojeto/cadastro_dos_doadores#7]
Após o usuário pesquisar pela sacolinha e adicionar ao registro de doação, o campo deve limpar a informação para que ele faça uma nova pesquisa.

Esse item não é um impedimento no funcionamento, mas proporcionará melhor usabilidade.

![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/147184432/0b6a398c-f51b-4913-9d99-4b5e7339485d)

**Comment by Glaugobira** [comment]
Quando salva o registro da doação, o sistema limpa somente alguns dados: a pesquisa da sacolinha e a célula permanecem com preenchimento

![image](https://github.com/guilhermeforprojeto/cadastro_dos_doadores/assets/147184432/0ad8d337-2b69-4f78-a45d-66f8d0f7f09c)

**Comment by guilhermeforprojeto** [comment]
Ajsutado commit:  `823315556456d61b88afe056b65711cf0c0c7725`

**Comment by guilhermeforprojeto** [comment]
agora ao adicionar a sacola o campo de pequisa limpa
